#!/usr/bin/env bash
# Jobcraft — tek komut kurulum.
#   ./install.sh
#
# Kurar: Bun, portal CLI'ler, poppler (pdftotext), TinyTeX (lualatex/xelatex),
# shell PATH, Python salary yardımcısı (openpyxl). Kullanıcı ekstra adım atmaz.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"

ok()   { printf '  \033[32mOK\033[0m   %s\n' "$*"; }
warn() { printf '  \033[33mWARN\033[0m %s\n' "$*"; }
fail() { printf '  \033[31mFAIL\033[0m %s\n' "$*"; exit 1; }
step() { printf '\n\033[1m==>\033[0m %s\n' "$*"; }

PORTALS=(linkedin-search kariyer-net-search yenibiris-search eleman-net-search)
ENV_FILE="$ROOT/scripts/jobcraft-env.sh"
MARKER='# Jobcraft (auto) — TinyTeX + Bun'

# ---------------------------------------------------------------------------
# PATH helpers
# ---------------------------------------------------------------------------
discover_tinytex_bin() {
  local d
  for d in \
    "$HOME/Library/TinyTeX/bin"/* \
    "$HOME/.TinyTeX/bin"/* \
    "$HOME/bin" \
    /usr/local/texlive/*/bin/*-darwin \
    /usr/local/texlive/*/bin/*-linux; do
    [[ -d "$d" ]] || continue
    [[ -x "$d/lualatex" || -x "$d/tlmgr" ]] || continue
    printf '%s' "$d"
    return 0
  done
  return 1
}

ensure_runtime_path() {
  local tiny
  tiny="$(discover_tinytex_bin 2>/dev/null || true)"
  if [[ -n "${tiny:-}" ]]; then
    export PATH="$tiny:$PATH"
  fi
  if [[ -d "$HOME/.bun/bin" ]]; then
    export PATH="$HOME/.bun/bin:$PATH"
  fi
  if [[ -x /opt/homebrew/bin/brew ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
  elif [[ -x /usr/local/bin/brew ]]; then
    eval "$(/usr/local/bin/brew shellenv)"
  fi
}

write_env_file() {
  local tiny bun_bin
  tiny="$(discover_tinytex_bin 2>/dev/null || true)"
  bun_bin=""
  if [[ -d "$HOME/.bun/bin" ]]; then
    bun_bin="$HOME/.bun/bin"
  fi

  mkdir -p "$(dirname "$ENV_FILE")"
  {
    echo "# Generated by ./install.sh — source this in non-login shells / agents."
    echo "# shellcheck disable=SC1091"
    if [[ -n "$bun_bin" ]]; then
      echo "export PATH=\"$bun_bin:\$PATH\""
    fi
    if [[ -n "${tiny:-}" ]]; then
      echo "export PATH=\"$tiny:\$PATH\""
    fi
    cat <<'EOF'
if [[ -x /opt/homebrew/bin/brew ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
elif [[ -x /usr/local/bin/brew ]]; then
  eval "$(/usr/local/bin/brew shellenv)"
fi
COOKIE_FILE="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)/jobcraft-cookies.local.sh"
if [[ -f "$COOKIE_FILE" ]]; then
  # shellcheck source=/dev/null
  source "$COOKIE_FILE"
fi
EOF
  } > "$ENV_FILE"
  ok "agent env → scripts/jobcraft-env.sh"
}

append_shell_rc() {
  local tiny bun_line tiny_line rc tmp
  tiny="$(discover_tinytex_bin 2>/dev/null || true)"
  bun_line='[[ -d "$HOME/.bun/bin" ]] && export PATH="$HOME/.bun/bin:$PATH"'
  tiny_line=""
  if [[ -n "${tiny:-}" ]]; then
    tiny_line="export PATH=\"$tiny:\$PATH\""
  fi

  for rc in "$HOME/.zshrc" "$HOME/.bashrc" "$HOME/.zprofile"; do
    if [[ ! -f "$rc" ]]; then
      touch "$rc"
    fi
    tmp="$(mktemp)"
    # Drop previous Jobcraft PATH blocks (new marker + legacy one-liner)
    awk '
      /^# Jobcraft \(auto\)/ { skip=1; next }
      skip && /^# Jobcraft end/ { skip=0; next }
      /^# Jobcraft \/ TinyTeX/ { skip=1; next }
      skip && /^export PATH=.*TinyTeX/ { skip=0; next }
      skip { next }
      { print }
    ' "$rc" > "$tmp"
    {
      echo ""
      echo "$MARKER"
      echo "$bun_line"
      if [[ -n "$tiny_line" ]]; then
        echo "$tiny_line"
      fi
      echo '# Jobcraft end'
    } >> "$tmp"
    mv "$tmp" "$rc"
    ok "PATH → $rc"
  done
}

# ---------------------------------------------------------------------------
# Installers
# ---------------------------------------------------------------------------
install_bun() {
  step "Bun"
  ensure_runtime_path
  if command -v bun >/dev/null 2>&1; then
    ok "bun $(bun --version) — $(command -v bun)"
    return 0
  fi
  echo "  Bun kuruluyor…"
  curl -fsSL https://bun.sh/install | bash
  ensure_runtime_path
  command -v bun >/dev/null || fail "bun kuruldu ama PATH'te yok — $HOME/.bun/bin kontrol et"
  ok "bun $(bun --version)"
}

install_python() {
  step "Python"
  if command -v python3 >/dev/null 2>&1; then
    ok "python3 $(python3 -c 'import sys; print("%d.%d"%sys.version_info[:2])')"
  else
    fail "python3 yok — macOS: xcode-select --install | Linux: apt install python3"
  fi
  # Salary Excel converter (optional but zero-friction)
  if python3 -c 'import openpyxl' 2>/dev/null; then
    ok "openpyxl hazır"
  else
    echo "  openpyxl kuruluyor (salary tool)…"
    python3 -m pip install --user -q openpyxl \
      && ok "openpyxl" \
      || warn "openpyxl atlandı — salary Excel dönüşümü opsiyonel"
  fi
  if python3 -c 'import curl_cffi' 2>/dev/null; then
    ok "curl_cffi hazır (Yenibiriş CF)"
  else
    echo "  curl_cffi kuruluyor (Yenibiriş Cloudflare)…"
    python3 -m pip install --user -q curl_cffi browser-cookie3 \
      && ok "curl_cffi + browser-cookie3" \
      || warn "curl_cffi atlandı — ./scripts/sync-yenibiris-cookie.sh manuel gerekebilir"
  fi
}

install_poppler() {
  step "poppler (pdftotext)"
  ensure_runtime_path
  if command -v pdftotext >/dev/null 2>&1; then
    ok "pdftotext — $(command -v pdftotext)"
    return 0
  fi
  if command -v brew >/dev/null 2>&1; then
    brew install poppler
    ensure_runtime_path
    command -v pdftotext >/dev/null || fail "poppler kuruldu ama pdftotext yok"
    ok "pdftotext — $(command -v pdftotext)"
  elif command -v apt-get >/dev/null 2>&1; then
    if [[ "$(id -u)" -eq 0 ]]; then
      apt-get update -qq && apt-get install -y -qq poppler-utils
    else
      sudo apt-get update -qq && sudo apt-get install -y -qq poppler-utils
    fi
    command -v pdftotext >/dev/null || fail "poppler-utils kuruldu ama pdftotext yok"
    ok "pdftotext — $(command -v pdftotext)"
  else
    warn "brew/apt yok — pdftotext atlandı (ATS kontrolü opsiyonel)"
  fi
}

install_latex() {
  step "LaTeX (TinyTeX)"
  ensure_runtime_path
  if command -v lualatex >/dev/null 2>&1 && command -v xelatex >/dev/null 2>&1; then
    ok "lualatex+xelatex hazır"
  else
    ensure_runtime_path
    if ! command -v tlmgr >/dev/null 2>&1; then
      echo "  TinyTeX indiriliyor (sudo istemez; PATH'i script yazar)…"
      # Official installer may try sudo for /etc/paths.d — ignore failure; we patch RC ourselves.
      curl -fsSL https://yihui.org/tinytex/install-bin-unix.sh | sh || true
    fi
    ensure_runtime_path
    command -v tlmgr >/dev/null 2>&1 || fail "tlmgr yok — TinyTeX kurulumu başarısız"
  fi

  echo "  moderncv + font paketleri…"
  tlmgr update --self >/dev/null 2>&1 || warn "tlmgr update --self atlandı"
  tlmgr install \
    moderncv fontawesome5 fontawesome6 academicons import luatexbase pgf \
    titlesec textpos xltxtra xunicode cite realscripts needspace \
    fontspec unicode-math xcolor geometry hyperref enumitem \
    microtype etoolbox graphics oberdiek tools latex-bin \
    collection-fontsrecommended \
    >/dev/null 2>&1 \
    || warn "bazı tlmgr paketleri zaten vardı / atlandı"

  ensure_runtime_path
  command -v lualatex >/dev/null || fail "lualatex yok"
  command -v xelatex >/dev/null || fail "xelatex yok"
  ok "lualatex — $(command -v lualatex)"
  ok "xelatex — $(command -v xelatex)"
}

setup_workspace_state() {
  step "Workspace state"
  mkdir -p job_scraper
  if [[ ! -f job_scraper/seen_jobs.json ]]; then
    if [[ -f job_scraper/seen_jobs.example.json ]]; then
      cp job_scraper/seen_jobs.example.json job_scraper/seen_jobs.json
      ok "job_scraper/seen_jobs.json (örnekten)"
    else
      printf '%s\n' '{"seen":{}}' > job_scraper/seen_jobs.json
      ok "job_scraper/seen_jobs.json (boş)"
    fi
  else
    ok "job_scraper/seen_jobs.json mevcut"
  fi
  if [[ ! -f salary_data.json && -f salary_data.sample.json ]]; then
    cp salary_data.sample.json salary_data.json
    ok "salary_data.json (sample — gerçek benchmark ile değiştir)"
  elif [[ -f salary_data.json ]]; then
    ok "salary_data.json mevcut"
  else
    warn "salary_data.json yok — /apply maaş adımı atlanır"
  fi
  if [[ ! -f job_search_tracker.csv ]]; then
    if [[ -f job_search_tracker.example.csv ]]; then
      cp job_search_tracker.example.csv job_search_tracker.csv
      ok "job_search_tracker.csv (örnekten — başvuru satırları /outcome ile)"
    else
      printf '%s\n' 'date,company,sector,role,role_type,channel,status,contact_person,fit_rating,notes,cv_file,cover_letter_file,source' > job_search_tracker.csv
      ok "job_search_tracker.csv (boş başlık)"
    fi
  else
    ok "job_search_tracker.csv mevcut"
  fi
  mkdir -p reports upskill documents/applications
}

install_portals() {
  step "Portal CLI'ler"
  ensure_runtime_path
  command -v bun >/dev/null || fail "bun gerekli"
  local tool dir
  for tool in "${PORTALS[@]}"; do
    dir=".agents/skills/$tool/cli"
    if [[ ! -d "$dir" ]]; then
      warn "skip — $dir yok"
      continue
    fi
    (cd "$dir" && bun install --silent)
    ok "$tool"
  done
}

smoke_latex() {
  step "Smoke test (örnek PDF)"
  ensure_runtime_path
  local log
  log="$(mktemp -t jobcraft-latex.XXXXXX)"
  if (cd cv && lualatex -interaction=nonstopmode -halt-on-error main_example.tex >"$log" 2>&1); then
    ok "cv/main_example.pdf"
  else
    warn "CV smoke başarısız — log: $log"
  fi
  if (cd cover_letters && xelatex -interaction=nonstopmode -halt-on-error cover_example.tex >"$log" 2>&1); then
    ok "cover_letters/cover_example.pdf"
  else
    warn "Cover smoke başarısız — log: $log"
  fi
}

setup_cookie_scaffold() {
  step "Portal cookie şablonu"
  local example="$ROOT/scripts/jobcraft-cookies.local.sh.example"
  local localf="$ROOT/scripts/jobcraft-cookies.local.sh"
  if [[ -f "$localf" ]]; then
    ok "jobcraft-cookies.local.sh mevcut"
  elif [[ -f "$example" ]]; then
    cp "$example" "$localf"
    chmod 600 "$localf"
    ok "jobcraft-cookies.local.sh oluşturuldu (şablon — Yenibiriş için doldur)"
  else
    warn "cookie şablonu yok — scripts/jobcraft-cookies.local.sh.example"
  fi
}

verify_all() {
  step "Doğrulama"
  ensure_runtime_path
  local missing=0
  for cmd in bun python3 lualatex xelatex; do
    if command -v "$cmd" >/dev/null 2>&1; then
      ok "$cmd"
    else
      warn "$cmd EKSİK"
      missing=1
    fi
  done
  if command -v pdftotext >/dev/null 2>&1; then
    ok "pdftotext"
  else
    warn "pdftotext yok (opsiyonel)"
  fi
  [[ "$missing" -eq 0 ]] || fail "zorunlu araçlar eksik — yukarıdaki WARN'lara bak"
}

# ---------------------------------------------------------------------------
printf '\033[1mJobcraft kurulum\033[0m\n'
printf 'Repo: %s\n' "$ROOT"

install_bun
install_python
install_poppler
install_latex
write_env_file
append_shell_rc
install_portals
setup_cookie_scaffold
setup_workspace_state
smoke_latex
verify_all

# shellcheck disable=SC1090
# shellcheck source=/dev/null
source "$ENV_FILE" 2>/dev/null || true

if [[ -z "${YENIBIRIS_COOKIE:-}" && -z "${JOBCRAFT_HTTP_COOKIE:-}" ]]; then
  warn "Yenibiriş cookie yok — ./scripts/setup-portal-auth.sh (3/4 portal /scrape için yeterli)"
else
  ok "Yenibiriş cookie yüklü"
fi

printf '\n\033[32mKurulum tamam.\033[0m Tekrar kurulum için yine:  ./install.sh\n\n'
cat <<'EOF'
Şimdi:
  1. Bu klasörü Cursor ile aç
  2. Agent chat'te / → setup, scrape, apply …
  3. ./scripts/setup-portal-auth.sh   → Yenibiriş cookie (Cloudflare — ilk kurulum)
  4. ./scripts/doctor.sh              → 4 portal canlı kontrol
  5. /setup   → profil
  6. /scrape  → iş ara
  7. /apply   → CV + ön yazı PDF

Agent / yeni shell:
  source scripts/jobcraft-env.sh

Cookie rehberi: docs/portal-authentication.md
Veri konumları: docs/tr-veri-konumlari.md

Profil (PII): cp profile.local.md.example profile.local.md  # gitignored
EOF
